config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :articles do
    resources :comments #add nested routes e.g. articles/:id/comments/:id
  end
  get '/about', to: 'index#about'
  get '/apps', to: 'index#apps'
  get '/photos', to: 'index#photos'
  get 'search', to: 'search#search'
  root to: "index#home"
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
include Orderable

class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy #if the article is deleted associated comments are deleted as well
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true
end

app/models/concerns/orderable.rb
module Orderable
  extend ActiveSupport::Concern
  def in_order
    order(created_at: :asc)
  end

  def get_neighbors
    [{name: 'next', operator: ">"}, {name: 'previous', operator: "<"}].each do | op |
      define_singleton_method (op[:name]) do |position|
        self.class.where("id #{op[:operator]} ?", self.id).send(position)
      end
    end
  end

  def recent(n)
    in_order.endmost(n)
  end

  def endmost(n)
    #TODO update so other types of artifacts can be used
    all.only(:order).from(all.reverse_order.limit(n), Article)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :resource_not_found
  helper_method :current_user, :logged_in?, :admin?
  protected;
  def resource_not_found
  end

  def logged_in?
    !!current_user
  end

  def admin?
    current_user.email == Rails.application.config.admin unless !current_user
  end

  def authenticate_user
    if !logged_in?
      flash[:danger] = "You must be signed in to do that!"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :update, :show, :edit, :destroy ]
  before_action :authenticate_user, except: [ :index, :show ]
  before_action :same_user, only: [ :update, :destroy ]


  def index
    @articles = Article.all.reverse
  end

  def new
    if !admin?
      redirect_to articles_path
    end
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been created!"
      render "new"
    end
  end

  def edit
    if !admin?
      redirect_to articles_path
    end
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
    else
      flash.now[:danger] = "Article has not been updated!"
      render "edit"
    end

  end

  def show
    @comments = @article.comments
    @comment = @article.comments.build
  end

  def destroy
    if admin?
      @article.destroy
    end
      redirect_to articles_path
  end

  protected;
  def resource_not_found
    message = "This is not the article you are looking for"
    flash[:alert] = message
    redirect_to root_path
  end

  private;
  def article_params
    params.require(:article).permit(:title, :body)
  end

  private;
  def set_article
    @article = Article.find(params[:id])
    @article.get_neighbors()
  end

  private;
  def same_user
    if @article.user != current_user
      flash[:danger] = "You cannot change other writers' articles"
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article

  def create
    unless current_user
      flash[:alert] = "Please sign in or sign up first"
      redirect_to new_user_session_path
    else
      @comment = @article.comments.build(comment_params)
      @comment.user = current_user
      if @comment.save
        ActionCable.server.broadcast "comments", render(partial: 'ui_modules/comment', object: @comment)
      else
        redirect_to article_path(@article)
      end

    end
  end

  private;
  def comment_params
    params.require(:comment).permit(:body)
  end

  private;
  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/concerns/keymaker/configuration.rb
module Keymaker

  class Configuration 

    include Singleton

    def self.field( field_name, options = {} )

      class_eval(
        "def #{ field_name }( *arguments ); " +
           "@#{ field_name } = arguments.first unless arguments.empty?; " +
           "@#{ field_name } || " +
             ( options[ :default ].blank? ?
                "nil" :
                ( options[ :default ].is_a?( String ) ? 
                    "'#{ options[ :default ] }'" : 
                      "#{ options[ :default ] }" ) ) + ";" +
        "end",
        __FILE__, 
        __LINE__
      )

    end

    field :url,              default: ENV[ 'KEYMAKER_URL' ]
    field :client_id,        default: ENV[ 'KEYMAKER_CLIENT' ]
    field :client_secret,    default: ENV[ 'KEYMAKER_SECRET' ]

  end

end

app/controllers/concerns/keymaker/operation.rb
module Keymaker

  class Operation
    
    attr_accessor :url, :client_id, :client_secret

    def initialize( params={} )
      self.url = params[ :url ]
      self.client_id = params[ :client_id ]
      self.client_secret = params[ :client_secret ]
    end

    def get( path, parameters={} )
      request( path, parameters, Net::HTTP::Get )
    end

    def post( path, parameters={} )
      request( path, parameters, Net::HTTP::Post )
    end  

    def request( path, parameters, operator )
      
      uri = URI( url + path )
      body = URI.encode_www_form( authenticated_params.merge( parameters ) )

      operation = operator.new( uri )

      operation.body = body

      result = nil

      response = Net::HTTP.start( uri.hostname, uri.port ) do |http|
        http.request( operation )
      end

      #check response and set result if valid
      if response &&
            response.is_a?( Net::HTTPSuccess ) &&
            response.body.present?
        result = JSON.parse( response.body )
      end

      result
    end
    def access_token
      @access_token ||= Unimatrix::Authorization::ClientCredentialsGrant.new(
        client_id: ENV[ 'KEYMAKER_CLIENT' ],
        client_secret: ENV[ 'KEYMAKER_SECRET' ]
      ).request_token
    end

    def authenticated_params
      { access_token: access_token }
    end

  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    @articles = Article.order(created_at: :desc).limit(5)
  end

  def about
  end

  def apps
  end

  def photos
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @articles = []
    else
      @articles = Article.search params[:q]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def persisted_comments(comments)
    comments.reject do |comment|
      comment.new_record?
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h3 class="text-center">Edit Article</h3>
  <%= render 'ui_modules/next_prev_links' %>
  <%= render 'ui_modules/form' %>
</div>

app/views/articles/index.html.erb
<div class="row pic-hero hero">
  <span class="section-title">
    Adventure Stories
  </span>
</div>
<br />
<div class="container index-container">
  <div class="index-description">
    Follow my blog for stories about my adventures in the Software and Engineering Industry. I also post tips
    and tricks in web and software development. More exciting content to come.
  </div><br />
  <%= render 'ui_modules/articles_list' %>
</div>
<%= render 'ui_modules/footer' %>

app/views/articles/new.html.erb
<div class="container">
  <h3 class="text-center">New Article</h3>
  <%= render 'ui_modules/form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <%= render 'ui_modules/next_prev_links' %>
  <div class="article-body">
    <h1 class="text-center"><%= @article.title %></h1>
    <h4 class="text-center">By: <%= @article.user.email %> | <%= @article.created_at.strftime("%B %e, %Y") %></h4><br />
    <% if user_signed_in? && admin? %>
      <div class="btn-center">
        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-sm btn-info" %> &emsp;
        <%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "Are you sure you want to delete this article?" } %>
      </div>
      <br />
    <% end %>
    <p><%= raw @article.body %></p>
  </div>
  <% if user_signed_in? %>
    <br />
    <%= render './ui_modules/comment_form' %>
  <% end %>

  <div class="col-md-12">
    <header>
      <h3>Comments</h3>
      <% if !user_signed_in? %>
        <em>
          <%= link_to "Sign in", new_user_session_path %> or
          <%= link_to "sign up", new_user_registration_path %> to comment
        </em>
      <% end %>
    </header>
    <hr />
    <div class="col-md-12">
      <% if @article.comments.any? %>
        <div id="messages">
          <% persisted_comments(@comments).each do |comment| %>
            <%= render './ui_modules/comment', :comment => comment %>
          <% end %>
        <% else %>
          There are no comments to show
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/index/about.html.erb
<div class="row about-hero hero">
  <span class="section-title">
    About The Clever Coder
  </span>
  <%= image_tag("face.jpg", class: "face") %>
</div>
<div class="intro container">
  <h2 align="left">Dominck Caponi</h2>
  <h4 align="left">Software Developer | Engineer | Leader</h4><br />
  <p>
    Defying the norms and experiencing all of what life
    has to offer are what I'm all about. I love exploring topics
    in Mechanical, Aerospace, and Software Engineering. I am a born
    tinkerer who is often found taking stuff apart and building
    cool stuff. I love working with and for startups where work isn't
    taken too seriously and my contributions to the team directly impact
    where what we put out into the world.
  </p>
  <p>
    I like to experience everything the Pacific Northwest has to offer
    and share my adventures in photos and blog posts. I also enjoy
    tinkering with electronics and Arduino boards. In addition, I like
    to play around with Android apps and build web apps in Ruby. the
    internet of things revolution is fascinating and I plan to learn
    how to develop for it as I build on my software development skills.
  </p>
  <p>
    I enjoy nerdy things like Star Wars, video games and theoretical discussions
    in computer science. I prefer tabs over spaces and my favorite
    languages include Java, Ruby, and AngularJS (although I am always adding
    languages to that stack such as C, Swift and Linux). I was a long time Windows
    user who recently converted to Apple, and I am still on the fence absolute
    Android vs IPhone.
  </p>
  <p>
    Not only do I love learning new things, but I also love sharing
    what I learn in my experiences studies. Every time I learn something
    that I found difficult, I like to share with my followers and friends
    so they too can take advantage of the amazing technologies available
    today. I hope you find this blog useful if you are stuck on a technical
    challenge or trying to make sense of your career in tech. I also hope
    you have as much fun reading this as I did making it.
  </p>
</div>
<%= render 'ui_modules/footer' %>

app/views/index/apps.html.erb
<div class="row app-hero hero">
  <span class="section-title">
    Software Applications
  </span>
</div>
<div class="container">
  <br />
  <h2 align="center">Beautiful, Efficient Apps</h2><br />
  <p>
    Each one of my apps is hand crafted using the freshest designs,
    organic code methods and free range imagination. Apps are coded in
    many web languages including Javascript, jQuery, AngularJS, and
    Ruby on Rails. Code for these apps is available on Github to view,
    fork or clone, incliding this blog, coded in Ruby on Rails.
  </p>
  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>Rapport Report</b></h4>
          <p>An app designed to give you a social media score</p>
          <ul>
            <li>Coded in jQuery</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/Rapport-Report" %></li>
            <li><%=link_to "Live Site", "http://dcaponi.github.io/Rapport-Report/" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>Zhijin Global Geopark</b></h4>
          <p>A beautiful example of my design and SEO focus</p>
          <ul>
            <li>Coded in javaScript</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/Design-Showcase" %></li>
            <li><%=link_to "Live Site", "http://dcaponi.github.io/Design-Showcase/" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>Pong 2.0</b></h4>
          <p>JavaScript based twist on Pong</p>
          <ul>
            <li>Coded in JavaScript</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/newPong" %></li>
            <li><%=link_to "Live Site", "http://dcaponi.github.io/newPong/" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>Spotifind</b></h4>
          <p>Suggests artists related to your favorite artists</p>
          <ul>
            <li>Coded in NodeJS</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/Spotifind" %></li>
            <li><%=link_to "Live Site", "https://sleepy-citadel-81588.herokuapp.com/" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>World Guidebook</b></h4>
          <p>An app that tells you about any country in the world</p>
          <ul>
            <li>Coded in AngularJS</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/country-cap-app" %></li>
            <li><%=link_to "Live Site", "http://www.dominick-caponi.com/CountryCapApp/#/" %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card">
        <div class="container">
          <%= image_tag("face.jpg", class: "app-img") %>
          <h4><b>Fitness Tracker</b></h4>
          <p>Keep track of and share your fitness goals and progress with your friends</p>
          <ul>
            <li>Coded in JavaScript</li>
            <li><%=link_to "Github", "https://github.com/dcaponi/fitness_tracker" %></li>
            <li>Work in Progress</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'ui_modules/footer' %>

app/views/index/home.html.erb
<div class="jumbotron">
  <div class="shade">
    <h1>The Clever Coder</h1>
    <p>Dare to do something new and dive into the unknown</p>
  </div><br />
  <% if !user_signed_in? %><button class="btn btn-lg btn-signup"><%= link_to "Sign Up", new_user_registration_path %></button><% end %>
  <button class="btn btn-lg btn-signup"><%= link_to "About", about_path %></button>
</div>
<div class="container">
  <h2>Recent Posts</h2><br />
  <%= render 'ui_modules/articles_list' %>
</div>
<%= render 'ui_modules/footer' %>

app/views/index/photos.html.erb
<div class="row pic-hero hero">
  <span class="section-title">
    Adventures in Photos
  </span>
</div>
<div class="container">
  <br />
  <h2>Photo page coming soon</h2>
</div>
<%= render 'ui_modules/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './ui_modules/nav' %>
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |key, msg| %>
          <div class="text-center alert alert-<%= key == 'success'? 'success' : 'danger' %>">
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/search/search.html.erb
<h1>Articles Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @articles.each do |article| %>
    <li>
      <h3>
        <%= link_to article.title, controller: "articles", action: "show", id: article._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/ui_modules/_articles_list.html.erb
<% @articles.each do |article| %>
  <div class="panel panel-default">
    <%= link_to article_path(article) do %>
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-8">
            <h2 class="panel-title"><%= article.title %></h2><br />
            <p>By: <%= article.user.email %>&nbsp; <%= time_ago_in_words(article.created_at) %> ago</p>
          </div>
          <div class="col-sm-4">
            <% if user_signed_in? && admin? %>
              <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-xs btn-danger actibutton", data: { confirm: "Are you sure you want to delete this article?" } %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-info actibutton" %>
              <%= link_to "View", article_path(article), class: "btn btn-xs btn-success actibutton" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    
    <%= link_to article_path(article) do %>
      <div class="panel-body row">
        <div class="col-sm-12">
          <%= raw (article.body).truncate(1000) %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/ui_modules/_comment.html.erb
<div class="comment-body">
  <%= comment.body %>
</div>
<div class="comment-time">
  <small>
    <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.email %>
  </small>
</div>
<hr />

app/views/ui_modules/_comment_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for [@article, @comment], remote: true, :html => {class: "form-horizontal", role: "form"} do |f| %>

      <% if @comment.errors.any? %>
        <%= render './ui_modules/errors', :object => @comment %>
      <% end %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :body, "New Comment" %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :body, rows: 3, class: "form-control", placeholder: "Comment" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-md pull-right" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ui_modules/_errors.html.erb
  <div class="panel panel-danger col-md-offset-1">
    <div class="panel-heading">
      <h2 class="panel-title"><%= pluralize(object.errors.count, "error")%> prevented saving</h2>
    </div>
    <div class="panel-body">
      <ul>
        <%= object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>

app/views/ui_modules/_footer.html.erb
<footer class="row">
  <div class="container">
    <br />
    <div class="row">
      <div class="col-xs-3">
        <a href="mailto:d.caponi1@gmail.com?Subject=Cool Blog">
          <i class="fa fa-envelope-o" aria-hidden="true"></i>
        </a>
      </div>
      <div class="col-xs-3">
        <a href="https://www.twitter.com/DominickCaponi">
          <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
      </div>
      <div class="col-xs-3">
        <a href="https://www.linkedin.com/in/dominickcaponi">
          <i class="fa fa-linkedin" aria-hidden="true"></i>
        </a>
      </div>
      <div class="col-xs-3">
        <a href="https://www.github.com/dcaponi">
          <i class="fa fa-github" aria-hidden="true"></i>
        </a>
      </div>
    </div><br />
    <div class="row">
      <p align="center">
        <a href="http://www.dominick-caponi.com">
          Copyright: &copy; 2017 Dominick Caponi - Software Developer
        </a>
      </p>
    </div>
    <br />
  </div>
</footer>

app/views/ui_modules/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for @article, :html => {class: "form-horizontal", role: "form"} do |f| %>

      <% if @article.errors.any? %>
        <%= render './ui_modules/errors', :object => @article %>
      <% end %>

      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= f.label :title %>
        </div>
        <div class="col-sm-11">
          <%= f.text_field :title, class: 'form-control', placeholder: "Article Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-1">
          <%= f.label :body %>
        </div>
        <div class="col-sm-11">
          <%= f.cktext_area :body, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: 'form-control', placeholder: "Article Content" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-1 col-md-11">
          <%= f.submit class: 'btn btn-primary btn-lg pull-right' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ui_modules/_nav.html.erb
<header role="banner">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Clever Coder", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
          <!-- <li><%= link_to "Apps", apps_path %></li> -->
          <li><%= link_to "Original Site", "http://www.dominick-caponi.com" %></li>
          <li><%= link_to "Blog", articles_path %></li>
          <!-- <li><%= link_to "Photography", photos_path %></li> -->

          <% if user_signed_in? && admin? %>
            <li><%= link_to "New Article", new_article_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/ui_modules/_next_prev_links.html.erb
<div style="float:left">
  <% if @article.previous( :last ).present? %>
      <%= link_to "Previous: " + @article.previous( :last ).title, article_path(@article.previous( :last )) %>
  <% end %>
  <% if @article.next( :last ).present? %>
      <%= link_to "Jump to Newest: " + @article.next( :last ).title, article_path(@article.next( :last )) %>
  <% end %>
</div>
<div style="float:right">
  <% if @article.next( :first ).present? %>
      <%= link_to "Up Next: " + @article.next( :first ).title, article_path(@article.next( :first )) %>
  <% end %>
  <% if @article.previous( :first ).present? %>
      <%= link_to "See First Article: " + @article.previous( :first ).title, article_path( @article.previous( :first ) ) %>
  <% end %>
</div>
<div class="clearfix"></div><br />